export const SET_USER = "SET_USER";
export const SET_THONG_TIN_NGUOI_DUNG = "SET_THONG_TIN_NGUOI_DUNG";
export const DELETE_THONG_TIN_USER = "DELETE_THONG_TIN_USER";
export const DELETE_THONG_TIN_NGUOI_DUNG = "DELETE_THONG_TIN_NGUOI_DUNG";